// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

package proto;

public final class ClientOuterClass {
  private ClientOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Gen}
   */
  public enum Gen
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MASCULIN = 0;</code>
     */
    MASCULIN(0),
    /**
     * <code>FEMININ = 1;</code>
     */
    FEMININ(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MASCULIN = 0;</code>
     */
    public static final int MASCULIN_VALUE = 0;
    /**
     * <code>FEMININ = 1;</code>
     */
    public static final int FEMININ_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Gen valueOf(int value) {
      return forNumber(value);
    }

    public static Gen forNumber(int value) {
      switch (value) {
        case 0: return MASCULIN;
        case 1: return FEMININ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Gen>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Gen> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Gen>() {
            public Gen findValueByNumber(int number) {
              return Gen.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ClientOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Gen[] VALUES = values();

    public static Gen valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Gen(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Gen)
  }

  public interface ClientOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Client)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nume = 1;</code>
     */
    java.lang.String getNume();
    /**
     * <code>string nume = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumeBytes();

    /**
     * <code>string CNP = 2;</code>
     */
    java.lang.String getCNP();
    /**
     * <code>string CNP = 2;</code>
     */
    com.google.protobuf.ByteString
        getCNPBytes();
  }
  /**
   * Protobuf type {@code Client}
   */
  public  static final class Client extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Client)
      ClientOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Client.newBuilder() to construct.
    private Client(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Client() {
      nume_ = "";
      cNP_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Client(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nume_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              cNP_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ClientOuterClass.internal_static_Client_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ClientOuterClass.internal_static_Client_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ClientOuterClass.Client.class, proto.ClientOuterClass.Client.Builder.class);
    }

    public static final int NUME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nume_;
    /**
     * <code>string nume = 1;</code>
     */
    public java.lang.String getNume() {
      java.lang.Object ref = nume_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nume_ = s;
        return s;
      }
    }
    /**
     * <code>string nume = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumeBytes() {
      java.lang.Object ref = nume_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nume_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CNP_FIELD_NUMBER = 2;
    private volatile java.lang.Object cNP_;
    /**
     * <code>string CNP = 2;</code>
     */
    public java.lang.String getCNP() {
      java.lang.Object ref = cNP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cNP_ = s;
        return s;
      }
    }
    /**
     * <code>string CNP = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCNPBytes() {
      java.lang.Object ref = cNP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cNP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nume_);
      }
      if (!getCNPBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cNP_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nume_);
      }
      if (!getCNPBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cNP_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ClientOuterClass.Client)) {
        return super.equals(obj);
      }
      proto.ClientOuterClass.Client other = (proto.ClientOuterClass.Client) obj;

      boolean result = true;
      result = result && getNume()
          .equals(other.getNume());
      result = result && getCNP()
          .equals(other.getCNP());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUME_FIELD_NUMBER;
      hash = (53 * hash) + getNume().hashCode();
      hash = (37 * hash) + CNP_FIELD_NUMBER;
      hash = (53 * hash) + getCNP().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ClientOuterClass.Client parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ClientOuterClass.Client parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ClientOuterClass.Client parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ClientOuterClass.Client parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ClientOuterClass.Client parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ClientOuterClass.Client parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ClientOuterClass.Client parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ClientOuterClass.Client parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ClientOuterClass.Client parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ClientOuterClass.Client parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ClientOuterClass.Client parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ClientOuterClass.Client parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ClientOuterClass.Client prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Client}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Client)
        proto.ClientOuterClass.ClientOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ClientOuterClass.internal_static_Client_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ClientOuterClass.internal_static_Client_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ClientOuterClass.Client.class, proto.ClientOuterClass.Client.Builder.class);
      }

      // Construct using proto.ClientOuterClass.Client.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nume_ = "";

        cNP_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ClientOuterClass.internal_static_Client_descriptor;
      }

      @java.lang.Override
      public proto.ClientOuterClass.Client getDefaultInstanceForType() {
        return proto.ClientOuterClass.Client.getDefaultInstance();
      }

      @java.lang.Override
      public proto.ClientOuterClass.Client build() {
        proto.ClientOuterClass.Client result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.ClientOuterClass.Client buildPartial() {
        proto.ClientOuterClass.Client result = new proto.ClientOuterClass.Client(this);
        result.nume_ = nume_;
        result.cNP_ = cNP_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ClientOuterClass.Client) {
          return mergeFrom((proto.ClientOuterClass.Client)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ClientOuterClass.Client other) {
        if (other == proto.ClientOuterClass.Client.getDefaultInstance()) return this;
        if (!other.getNume().isEmpty()) {
          nume_ = other.nume_;
          onChanged();
        }
        if (!other.getCNP().isEmpty()) {
          cNP_ = other.cNP_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ClientOuterClass.Client parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ClientOuterClass.Client) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nume_ = "";
      /**
       * <code>string nume = 1;</code>
       */
      public java.lang.String getNume() {
        java.lang.Object ref = nume_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nume_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nume = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumeBytes() {
        java.lang.Object ref = nume_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nume_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nume = 1;</code>
       */
      public Builder setNume(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nume = 1;</code>
       */
      public Builder clearNume() {
        
        nume_ = getDefaultInstance().getNume();
        onChanged();
        return this;
      }
      /**
       * <code>string nume = 1;</code>
       */
      public Builder setNumeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nume_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cNP_ = "";
      /**
       * <code>string CNP = 2;</code>
       */
      public java.lang.String getCNP() {
        java.lang.Object ref = cNP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cNP_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string CNP = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCNPBytes() {
        java.lang.Object ref = cNP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cNP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string CNP = 2;</code>
       */
      public Builder setCNP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cNP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string CNP = 2;</code>
       */
      public Builder clearCNP() {
        
        cNP_ = getDefaultInstance().getCNP();
        onChanged();
        return this;
      }
      /**
       * <code>string CNP = 2;</code>
       */
      public Builder setCNPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cNP_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Client)
    }

    // @@protoc_insertion_point(class_scope:Client)
    private static final proto.ClientOuterClass.Client DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ClientOuterClass.Client();
    }

    public static proto.ClientOuterClass.Client getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Client>
        PARSER = new com.google.protobuf.AbstractParser<Client>() {
      @java.lang.Override
      public Client parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Client(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Client> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Client> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.ClientOuterClass.Client getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClientResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nume = 1;</code>
     */
    java.lang.String getNume();
    /**
     * <code>string nume = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumeBytes();

    /**
     * <code>.Gen gen = 2;</code>
     */
    int getGenValue();
    /**
     * <code>.Gen gen = 2;</code>
     */
    proto.ClientOuterClass.Gen getGen();

    /**
     * <code>int32 varsta = 3;</code>
     */
    int getVarsta();
  }
  /**
   * Protobuf type {@code ClientResponse}
   */
  public  static final class ClientResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientResponse)
      ClientResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientResponse.newBuilder() to construct.
    private ClientResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientResponse() {
      nume_ = "";
      gen_ = 0;
      varsta_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ClientResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nume_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              gen_ = rawValue;
              break;
            }
            case 24: {

              varsta_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ClientOuterClass.internal_static_ClientResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ClientOuterClass.internal_static_ClientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.ClientOuterClass.ClientResponse.class, proto.ClientOuterClass.ClientResponse.Builder.class);
    }

    public static final int NUME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nume_;
    /**
     * <code>string nume = 1;</code>
     */
    public java.lang.String getNume() {
      java.lang.Object ref = nume_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nume_ = s;
        return s;
      }
    }
    /**
     * <code>string nume = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumeBytes() {
      java.lang.Object ref = nume_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nume_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GEN_FIELD_NUMBER = 2;
    private int gen_;
    /**
     * <code>.Gen gen = 2;</code>
     */
    public int getGenValue() {
      return gen_;
    }
    /**
     * <code>.Gen gen = 2;</code>
     */
    public proto.ClientOuterClass.Gen getGen() {
      @SuppressWarnings("deprecation")
      proto.ClientOuterClass.Gen result = proto.ClientOuterClass.Gen.valueOf(gen_);
      return result == null ? proto.ClientOuterClass.Gen.UNRECOGNIZED : result;
    }

    public static final int VARSTA_FIELD_NUMBER = 3;
    private int varsta_;
    /**
     * <code>int32 varsta = 3;</code>
     */
    public int getVarsta() {
      return varsta_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nume_);
      }
      if (gen_ != proto.ClientOuterClass.Gen.MASCULIN.getNumber()) {
        output.writeEnum(2, gen_);
      }
      if (varsta_ != 0) {
        output.writeInt32(3, varsta_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nume_);
      }
      if (gen_ != proto.ClientOuterClass.Gen.MASCULIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, gen_);
      }
      if (varsta_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, varsta_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.ClientOuterClass.ClientResponse)) {
        return super.equals(obj);
      }
      proto.ClientOuterClass.ClientResponse other = (proto.ClientOuterClass.ClientResponse) obj;

      boolean result = true;
      result = result && getNume()
          .equals(other.getNume());
      result = result && gen_ == other.gen_;
      result = result && (getVarsta()
          == other.getVarsta());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUME_FIELD_NUMBER;
      hash = (53 * hash) + getNume().hashCode();
      hash = (37 * hash) + GEN_FIELD_NUMBER;
      hash = (53 * hash) + gen_;
      hash = (37 * hash) + VARSTA_FIELD_NUMBER;
      hash = (53 * hash) + getVarsta();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.ClientOuterClass.ClientResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ClientOuterClass.ClientResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.ClientOuterClass.ClientResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.ClientOuterClass.ClientResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.ClientOuterClass.ClientResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientResponse)
        proto.ClientOuterClass.ClientResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ClientOuterClass.internal_static_ClientResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ClientOuterClass.internal_static_ClientResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.ClientOuterClass.ClientResponse.class, proto.ClientOuterClass.ClientResponse.Builder.class);
      }

      // Construct using proto.ClientOuterClass.ClientResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nume_ = "";

        gen_ = 0;

        varsta_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ClientOuterClass.internal_static_ClientResponse_descriptor;
      }

      @java.lang.Override
      public proto.ClientOuterClass.ClientResponse getDefaultInstanceForType() {
        return proto.ClientOuterClass.ClientResponse.getDefaultInstance();
      }

      @java.lang.Override
      public proto.ClientOuterClass.ClientResponse build() {
        proto.ClientOuterClass.ClientResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.ClientOuterClass.ClientResponse buildPartial() {
        proto.ClientOuterClass.ClientResponse result = new proto.ClientOuterClass.ClientResponse(this);
        result.nume_ = nume_;
        result.gen_ = gen_;
        result.varsta_ = varsta_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ClientOuterClass.ClientResponse) {
          return mergeFrom((proto.ClientOuterClass.ClientResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.ClientOuterClass.ClientResponse other) {
        if (other == proto.ClientOuterClass.ClientResponse.getDefaultInstance()) return this;
        if (!other.getNume().isEmpty()) {
          nume_ = other.nume_;
          onChanged();
        }
        if (other.gen_ != 0) {
          setGenValue(other.getGenValue());
        }
        if (other.getVarsta() != 0) {
          setVarsta(other.getVarsta());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ClientOuterClass.ClientResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ClientOuterClass.ClientResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nume_ = "";
      /**
       * <code>string nume = 1;</code>
       */
      public java.lang.String getNume() {
        java.lang.Object ref = nume_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nume_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nume = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumeBytes() {
        java.lang.Object ref = nume_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nume_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nume = 1;</code>
       */
      public Builder setNume(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nume = 1;</code>
       */
      public Builder clearNume() {
        
        nume_ = getDefaultInstance().getNume();
        onChanged();
        return this;
      }
      /**
       * <code>string nume = 1;</code>
       */
      public Builder setNumeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nume_ = value;
        onChanged();
        return this;
      }

      private int gen_ = 0;
      /**
       * <code>.Gen gen = 2;</code>
       */
      public int getGenValue() {
        return gen_;
      }
      /**
       * <code>.Gen gen = 2;</code>
       */
      public Builder setGenValue(int value) {
        gen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Gen gen = 2;</code>
       */
      public proto.ClientOuterClass.Gen getGen() {
        @SuppressWarnings("deprecation")
        proto.ClientOuterClass.Gen result = proto.ClientOuterClass.Gen.valueOf(gen_);
        return result == null ? proto.ClientOuterClass.Gen.UNRECOGNIZED : result;
      }
      /**
       * <code>.Gen gen = 2;</code>
       */
      public Builder setGen(proto.ClientOuterClass.Gen value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gen_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Gen gen = 2;</code>
       */
      public Builder clearGen() {
        
        gen_ = 0;
        onChanged();
        return this;
      }

      private int varsta_ ;
      /**
       * <code>int32 varsta = 3;</code>
       */
      public int getVarsta() {
        return varsta_;
      }
      /**
       * <code>int32 varsta = 3;</code>
       */
      public Builder setVarsta(int value) {
        
        varsta_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 varsta = 3;</code>
       */
      public Builder clearVarsta() {
        
        varsta_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientResponse)
    }

    // @@protoc_insertion_point(class_scope:ClientResponse)
    private static final proto.ClientOuterClass.ClientResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.ClientOuterClass.ClientResponse();
    }

    public static proto.ClientOuterClass.ClientResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientResponse>
        PARSER = new com.google.protobuf.AbstractParser<ClientResponse>() {
      @java.lang.Override
      public ClientResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ClientResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.ClientOuterClass.ClientResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Client.proto\032\031google/protobuf/any.prot" +
      "o\"#\n\006Client\022\014\n\004nume\030\001 \001(\t\022\013\n\003CNP\030\002 \001(\t\"A" +
      "\n\016ClientResponse\022\014\n\004nume\030\001 \001(\t\022\021\n\003gen\030\002 " +
      "\001(\0162\004.Gen\022\016\n\006varsta\030\003 \001(\005* \n\003Gen\022\014\n\010MASC" +
      "ULIN\020\000\022\013\n\007FEMININ\020\00123\n\014tema1Service\022#\n\007g" +
      "etInfo\022\007.Client\032\017.ClientResponseB\007\n\005prot" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Nume", "CNP", });
    internal_static_ClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientResponse_descriptor,
        new java.lang.String[] { "Nume", "Gen", "Varsta", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
